#!/bin/sh

    
case "$(echo -e "Shutdown\nRestart\nLogout\nSuspend\nLock" | dmenu \
    -i -p \
    "Power:" -l 5)" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Logout) kill -HUP $XDG_SESSION_PID;;
        Suspend) exec systemctl suspend;;
        Lock) exec i3lock;;
esac
