# font settings
font_size 11
active_tab_font_style bold
inactive_tab_font_style normal

# tab bar stuff
tab_bar_align left
tab_bar_edge bottom
tab_bar_style powerline
tab_bar_margin_width 0.0
tab_powerline_style slanted
enabled_layouts splits, stack
tab_title_template "{index}: {title}{sup.num_windows if num_windows > 1 else ''}{activity_symbol}{bell_symbol}"

# always show tab bar
tab_bar_min_tabs 1

# macos stuff
macos_option_as_alt yes

# set shell to nu
shell nu

# keymaps
# this emulates zooming panes
map ctrl+s>z toggle_layout stack

# create new panes
map ctrl+s>- launch --location=hsplit --cwd=current
map ctrl+s>\ launch --location=vsplit --cwd=current

# jump to other panes
map ctrl+s>h neighboring_window left
map ctrl+s>l neighboring_window right
map ctrl+s>k neighboring_window up
map ctrl+s>j neighboring_window down
map ctrl+s>q focus_visible_window

# move panes
map ctrl+s>ctrl+k move_window up
map ctrl+s>ctrl+h move_window left
map ctrl+s>ctrl+l move_window right
map ctrl+s>ctrl+j move_window down

# manipulate panes
map ctrl+s>ctrl+r start_resizing_window
map ctrl+s>r layout_action rotate
map ctrl+s>x close_window

# open ui panel to move the pane somewhere else
map ctrl+s>m detach_window ask

# show index for easier switching, show number of panes
map ctrl+s>c launch --type=tab --cwd=current
map ctrl+s>n next_tab
map ctrl+s>p previous_tab
map ctrl+s>1 goto_tab 1
map ctrl+s>2 goto_tab 2
map ctrl+s>3 goto_tab 3
map ctrl+s>4 goto_tab 4
map ctrl+s>5 goto_tab 5
map ctrl+s>6 goto_tab 6
map ctrl+s>7 goto_tab 7
map ctrl+s>8 goto_tab 8
map ctrl+s>9 goto_tab 9
map ctrl+s>0 goto_tab -1

map super+1 goto_tab 1
map super+2 goto_tab 2
map super+3 goto_tab 3
map super+4 goto_tab 4
map super+5 goto_tab 5
map super+6 goto_tab 6
map super+7 goto_tab 7
map super+8 goto_tab 8
map super+9 goto_tab 9
map super+0 goto_tab -1

map alt+enter toggle_fullscreen

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="BlexMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
