set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"
set -s escape-time 0

set-option -g focus-events on

set-option -g display-time 3000

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

unbind %
bind \\ split-window -h

unbind '"'
bind - split-window -v

bind r source-file ~/.config/tmux/tmux.conf

set -g status-position top
set -g base-index 1
set -g detach-on-destroy off
bind-key x kill-pane
set -g escape-time 0
set -g history-limit 1000000
set -g mouse on
set -g renumber-windows on
set -g set-clipboard on
set -g status-interval 3

set-window-option -g mode-keys vi

bind-key "f" run-shell "sesh connect \"$(
  sesh list | fzf-tmux -p 55%,60% \
    --no-sort --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""

bind-key -r F run-shell "sesh connect flake"
bind-key -r N run-shell "sesh connect nvim"
