{
  imports = [
    ./browsers.nix
    ./colorscheme-sync.nix
    ./fish.nix
    ./fonts.nix
    ./emacs.nix
    ./ghostty.nix
    ./git.nix
    ./gnome.nix
    ./gpg.nix
    ./gtk.nix
    ./helix.nix
    ./kubernetes.nix
    ./media.nix
    ./neovim.nix
    ./rice.nix
    ./sway.nix
    ./tmux.nix
    ./vscode.nix
    ./wezterm.nix
    ./zellij.nix
    ./zsh.nix
  ];
}
