name: Build Demo Dockerfile

on: [workflow_dispatch]

permissions:
  actions: write

jobs:
  build-demo-dockerfile:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: dotfiles
          image-tag: latest
